Repository TheGuyDangerous/FoodCoders, pull requests merged in 2022-10, with the labels that each got.

#15 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest, Hacktoberfest accepted

#17 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest, Hacktoberfest accepted

#20 Added 4rth Page
  Page-3-Veg.html
  Page-4-Veg.css
  Page-4-Veg.html
  Vegetarian.html
  images/chicken-butter-masala.jpeg
Labels: hacktoberfest, Hacktoberfest accepted

#23 added Google chrome extension along with logo
  images/logo-128.png
  images/logo-16.png
  images/logo-48.png
  manifest.json
Labels: hacktoberfest, Hacktoberfest accepted

#32 license, contributing, issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  LICENSE.md
Labels: documentation, good first issue, hacktoberfest, Hacktoberfest accepted

#34 Favicons Added To Home , Recipe and About pages
  About.html
  Home.html
  Vegetarian.html
  abtico.ico
  homeico.ico
  vegico.ico
Labels: hacktoberfest, Hacktoberfest accepted

#43 Added 6th Page
  Page-5-Veg.html
  Page-6-Veg.css
  Page-6-Veg.html
Labels: enhancement, good first issue, hacktoberfest, Hacktoberfest accepted

#49 updated favicon for every page
  Home.html
  Page-2-Veg.html
  Page-3-Veg.html
  Page-4-Veg.html
  Page-5-Veg.html
  Page-6-Veg.html
  Page-7-Veg.html
  Vegetarian.html
  images/FC.png
  index.html
Labels: enhancement, good first issue, hacktoberfest, Hacktoberfest accepted

#51 Contact added
  About.html
  Contact.css
  Contact.html
  Home.html
  Vegetarian.html
  index.html
Labels: enhancement, help wanted, hacktoberfest, Hacktoberfest accepted

#53 slider added to the Index page
  carousel.css
  carousel.js
  index.html
Labels: hacktoberfest, Hacktoberfest accepted

#56 added animation on the home page
  Home.css
  index.html
Labels: hacktoberfest, Hacktoberfest accepted

#58 Contact added
  About.html
  Contact.css
  Contact.html
  Home.html
  Vegetarian.html
  index.html
Labels: enhancement, hacktoberfest, Hacktoberfest accepted

#64 Added Page 9. Fixed button routings
  Page-8-Veg.html
  Page-9-Veg.css
  Page-9-Veg.html
  images/dahi-kachori.jpg
  images/fettucine-alfredo.jpeg
  images/lasagna.webp
  images/macaroons.webp
  images/missal-pav.jpg
  images/rumali-roti.jpg
Labels: enhancement, good first issue, hacktoberfest, Hacktoberfest accepted

#62 contact update3
  About.html
  Contact.css
  Contact.html
  Home.html
  Vegetarian.html
  index.html
Labels: enhancement, hacktoberfest, Hacktoberfest accepted

#61 Added Progressbar on homepage
  Home.css
  index.html
  noobcoders.js
Labels: good first issue, hacktoberfest, Hacktoberfest accepted

#66 Added progressbar in all pages
  About.css
  About.html
  Contact.css
  Contact.html
  Home.html
  Page-2-Veg.html
  Page-3-Veg.html
  Page-4-Veg.html
  Page-5-Veg.html
  Page-6-Veg.html
  Page-7-Veg.html
  Page-8-Veg.html
  Page-9-Veg.html
  Vegetarian.html
  noobcoders.css
Labels: enhancement, good first issue, hacktoberfest, Hacktoberfest accepted

#79 Updated Footer UI and About Page, fix page 5
  About.css
  About.html
  Contact.html
  Page-2-Veg.html
  Page-3-Veg.html
  Page-4-Veg.html
  Page-5-Veg.html
  Page-6-Veg.html
  Page-7-Veg.html
  Page-8-Veg.html
  Page-9-Veg.html
  Vegetarian.html
  images/Iconnew-removebg-preview.png
  index.html
Labels: bug, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#73 Login and signup page added
  index.html
  login.css
  login.html
  register.html
Labels: hacktoberfest, hacktoberfest-accepted

#87 Added zoom in animations to images on vegetarian.html
  Page-10-Veg.css
  Page-10-Veg.html
  Page-2-Veg.css
  Page-2-Veg.html
  Page-3-Veg.css
  Page-3-Veg.html
  Page-4-Veg.css
  Page-4-Veg.html
  Page-5-Veg.css
  Page-5-Veg.html
  Page-6-Veg.css
  Page-6-Veg.html
  Page-7-Veg.css
  Page-7-Veg.html
  Page-8-Veg.css
  Page-8-Veg.html
  Page-9-Veg.css
  Page-9-Veg.html
  Vegetarian.css
  Vegetarian.html
  page-11-veg.css
  page-11-veg.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#92 enhanced-contactpage
  Contact.css
  Contact.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#96 Updated Readme
  README.md
  images/page-contact.png
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#98 added responsiveness in home page for medium device
  Home.css
  carousel.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#99 Fixed a bug where the css was not loading in properly
  Page-10-Veg.html
  Page-11-Veg.html
  Page-2-Veg.html
  Page-3-Veg.html
  Page-4-Veg.html
  Page-5-Veg.html
  Page-6-Veg.html
  Page-7-Veg.html
  Page-8-Veg.html
  Page-9-Veg.html
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#100 added defferent looks for medium and small devices in contact page
  Contact.html
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted
