Repository TheGuyDangerous/FoodCoders, pull requests merged in 2024-10, with the labels that each got.

#127 added 6 new recipes
  html-files/pages/Page16.html
  html-files/pages/Page17.html
  images/Page 17/Avocado Toast.png
  images/Page 17/Eggs Benedict.png
  images/Page 17/Oatmeal.png
  images/Page 17/Pancakes.png
  images/Page 17/Shakshuka.png
  images/Page 17/Smoothie Bowl.png
Labels: good first issue, hacktoberfest, Hacktoberfest accepted, hacktoberfest-accepted, approved

#128 Fixed the bug of signup pages
  index.html
Labels: bug, good first issue, hacktoberfest, Hacktoberfest accepted, hacktoberfest-accepted, approved

#132 redirect bug fixed
  index.html
Labels: bug, good first issue, hacktoberfest, Hacktoberfest accepted, hacktoberfest-accepted, approved

#134 Improved Navbar and Responsiveness
  css/page-css/homepage/main.css
  css/page-css/homepage/navbar.css
  css/page-css/noobcoders.css
  css/recipe-pages/page-content-design.css
  html-files/pages/Page1.html
  html-files/pages/Page10.html
  html-files/pages/Page11.html
  html-files/pages/Page12.html
  html-files/pages/Page13.html
  html-files/pages/Page14.html
  html-files/pages/Page15.html
  html-files/pages/Page16.html
  html-files/pages/Page17.html
  html-files/pages/Page18.html
  html-files/pages/Page2.html
  html-files/pages/Page3.html
  html-files/pages/Page4.html
  html-files/pages/Page5.html
  html-files/pages/Page6.html
  html-files/pages/Page7.html
  html-files/pages/Page8.html
  html-files/pages/Page9.html
  html-files/support-pages/About.html
  html-files/support-pages/Contact.html
  images/Remini20211005111607851-removebg1.png
  js/navbar.js
Labels: bug, enhancement, good first issue, hacktoberfest, Hacktoberfest accepted, hacktoberfest-accepted, approved
